import Foundation

/// Curated list of 70 Best Food Podcasts
/// Source: FeedSpot - https://podcast.feedspot.com/food_podcasts/
struct FoodPodcastsData {

    /// All 70 food podcasts from the curated list
    static let allPodcasts: [FoodPodcastEntry] = [
        FoodPodcastEntry(
            rank: 1,
            name: "Table Manners with Jessie and Lennie Ware",
            hosts: ["Jessie Ware", "Lennie Ware"],
            producer: "Jessie Ware",
            appleRating: 4.8,
            appleReviews: 13700,
            avgLengthMinutes: 51,
            format: "Long form",
            since: "Nov 2017",
            description: "Jessie Ware hosts a podcast about food, family and everything in between.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 2,
            name: "Good Food",
            hosts: ["Samuel Goldsmith"],
            producer: "Good Food",
            appleRating: 4.8,
            appleReviews: 246,
            avgLengthMinutes: 33,
            format: "Medium form",
            since: nil,
            description: "Join host Samuel Goldsmith every Tuesday as he chats with cooks, chefs, and food lovers.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 3,
            name: "Christopher Kimball's Milk Street Radio",
            hosts: ["Christopher Kimball", "Sara Moulton"],
            producer: "Milk Street Radio",
            appleRating: 4.2,
            appleReviews: 2900,
            avgLengthMinutes: 49,
            format: "Long form",
            since: nil,
            description: "Every week, Milk Street Radio travels the world to find the most fascinating stories about food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 4,
            name: "Food Network Obsessed",
            hosts: ["Jaymee Sire"],
            producer: "Food Network",
            appleRating: 4.8,
            appleReviews: 466,
            avgLengthMinutes: 42,
            format: "Long form",
            since: "Dec 2020",
            description: "Each week on Food Network Obsessed, host Jaymee Sire sits down with your favorite Food Network stars.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 5,
            name: "Radio Cherry Bombe",
            hosts: ["Kerry Diamond"],
            producer: "The Cherry Bombe Network",
            appleRating: 4.7,
            appleReviews: 692,
            avgLengthMinutes: 43,
            format: "Long form",
            since: "May 2014",
            description: "Radio Cherry Bombe features interviews with the most interesting people in the world of food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 6,
            name: "Good Food",
            hosts: ["Evan Kleiman"],
            producer: "KCRW",
            appleRating: 4.6,
            appleReviews: 1200,
            avgLengthMinutes: 57,
            format: "Long form",
            since: nil,
            description: "Everything you wanted to know about good cooking and good eating from LA chef, author, radio host and restaurateur Evan Kleiman.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 7,
            name: "Savor",
            hosts: ["Anney Reese", "Lauren Vogelbaum"],
            producer: "iHeartPodcasts",
            appleRating: 4.3,
            appleReviews: 1800,
            avgLengthMinutes: 36,
            format: "Medium form",
            since: "Feb 2017",
            description: "Savor digs into how people live and how they eat and why.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 8,
            name: "Gastropod",
            hosts: ["Cynthia Graber", "Nicola Twilley"],
            producer: "Vox Media Podcast Network",
            appleRating: 4.7,
            appleReviews: 4600,
            avgLengthMinutes: 49,
            format: "Long form",
            since: "Sep 2014",
            description: "Food with a side of science and history. Every other week, co-hosts Cynthia Graber and Nicola Twilley explore food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 9,
            name: "Right at the Fork",
            hosts: ["Chris Angelus", "Cort Johnson"],
            producer: "RATF",
            appleRating: 4.7,
            appleReviews: 48,
            avgLengthMinutes: 75,
            format: "Long form",
            since: nil,
            description: "Think Portland, Oregon is all VooDoo Doughnuts and 'put an egg on it?' One of Portland's best food podcasts.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 10,
            name: "Food 101",
            hosts: ["Daniel Lucas", "Alessandro Panattoni"],
            producer: "Daniel Lucas/Alessandro Panattoni",
            appleRating: 4.9,
            appleReviews: 55,
            avgLengthMinutes: 22,
            format: "Medium form",
            since: nil,
            description: "Feasting on Sound the Ultimate Podcast for Food Lovers. Dive into the world of culinary arts, taste secrets, and kitchen hacks.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 11,
            name: "Heaping Spoonful",
            hosts: ["Ben E. Keith"],
            producer: "Ben E. Keith Mid-South",
            appleRating: 5.0,
            appleReviews: 16,
            avgLengthMinutes: 64,
            format: "Long form",
            since: "Sep 2019",
            description: "'Heaping Spoonful' is a twice-monthly conversation with restaurateurs, chefs, growers.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 12,
            name: "Hungry Girl: Chew the Right Thing!",
            hosts: ["Lisa Lillien"],
            producer: "Lisa Lillien",
            appleRating: 4.6,
            appleReviews: 987,
            avgLengthMinutes: 43,
            format: "Long form",
            since: "May 2018",
            description: "Lisa Lillien, a.k.a. Hungry Girl, is obsessed with food how wonderful it is, and how much we all love it.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 13,
            name: "Diabetes Digital Podcast by Food Heaven",
            hosts: ["Wendy Lopez", "Jessica Jones"],
            producer: "Wendy Lopez, Jessica Jones",
            appleRating: 4.9,
            appleReviews: 2500,
            avgLengthMinutes: 19,
            format: "Short form",
            since: nil,
            description: "Join BFFs, registered dietitian nutritionists, and diabetes educators Wendy Lopez and Jessica Jones.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 14,
            name: "It's All About Food",
            hosts: ["Caryn Hartglass"],
            producer: "Progressive Radio Network",
            appleRating: 4.6,
            appleReviews: 37,
            avgLengthMinutes: 58,
            format: "Long form",
            since: nil,
            description: "Since 2009, It's All About Food, a vegan podcast, has been bringing you the best in up-to-date information.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 15,
            name: "Straight To The Source",
            hosts: ["Tawnya Bahr", "Lucy Allon"],
            producer: "Food, Views and Big Ideas",
            appleRating: 5.0,
            appleReviews: 16,
            avgLengthMinutes: 39,
            format: "Medium form",
            since: nil,
            description: "Welcome to Food, Views and Big Ideas where food and hospitality experts share insights.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 16,
            name: "The Spoon Podcast",
            hosts: ["Michael Wolf"],
            producer: "The Spoon Podcast Network",
            appleRating: 4.8,
            appleReviews: 22,
            avgLengthMinutes: 37,
            format: "Medium form",
            since: nil,
            description: "Join host Michael Wolf and the Spoon editors as they explore the world of food tech, future food, ag tech and more!",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 17,
            name: "The Menu",
            hosts: ["Josh Fehnert", "Chiara Rimella"],
            producer: "Monocle Radio",
            appleRating: 4.2,
            appleReviews: 185,
            avgLengthMinutes: 20,
            format: "Short form",
            since: nil,
            description: "Our guide to the world of food, drink and entertaining, The Menu serves up interviews.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 18,
            name: "Doughboys",
            hosts: ["Mike Mitchell", "Nick Wiger"],
            producer: "Headgum",
            appleRating: 4.8,
            appleReviews: 5800,
            avgLengthMinutes: 132,
            format: "Extended",
            since: "May 2015",
            description: "The podcast about chain restaurants. Comedians Mike Mitchell and Nick Wiger review fast food/sit-down chains.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 19,
            name: "Eat Capture Share - a podcast for food bloggers",
            hosts: ["Kimberly Espinel"],
            producer: "Kimberly Espinel",
            appleRating: 4.8,
            appleReviews: 108,
            avgLengthMinutes: 46,
            format: "Long form",
            since: nil,
            description: "Do you love food, photography and social media? Are you a food photographer, food blogger?",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 20,
            name: "Find Your Food Voice",
            hosts: ["Julie Duffy Dillon"],
            producer: "Julie Duffy Dillon RDN",
            appleRating: 4.9,
            appleReviews: 887,
            avgLengthMinutes: 36,
            format: "Medium form",
            since: nil,
            description: "Find Your Food Voice is a podcast—and a movement—to fix diet culture.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 21,
            name: "Inside Julia's Kitchen",
            hosts: ["Todd Schulkin"],
            producer: "Heritage Radio Network",
            appleRating: 4.4,
            appleReviews: 99,
            avgLengthMinutes: 50,
            format: "Long form",
            since: "Jan 2018",
            description: "Created by The Julia Child Foundation for Gastronomy and the Culinary Arts.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 22,
            name: "Copper & Heat Radio",
            hosts: ["Katy Osuna"],
            producer: "Copper & Heat",
            appleRating: 4.9,
            appleReviews: 120,
            avgLengthMinutes: 41,
            format: "Long form",
            since: "Jul 2018",
            description: "Copper & Heat Radio explores the forces that shape our meals through narrative, sound-rich podcasts. James Beard, Signal, and IACP Award winner.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 23,
            name: "Lecker",
            hosts: ["Lucy Dearlove"],
            producer: "Lucy Dearlove",
            appleRating: 4.5,
            appleReviews: 88,
            avgLengthMinutes: 46,
            format: "Long form",
            since: "Sep 2016",
            description: "A podcast documenting cooking, eating and domestic life.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 24,
            name: "On The Pass",
            hosts: ["Gabriel Ornelas"],
            producer: "Gabriel Ornelas",
            appleRating: 4.9,
            appleReviews: 160,
            avgLengthMinutes: 49,
            format: "Long form",
            since: "Mar 2020",
            description: "On The Pass serves up inspiring conversations with dynamic figures in the food beverage, hospitality and travel space.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 25,
            name: "A Taste of the Past",
            hosts: ["Linda Pelaccio"],
            producer: "Heritage Radio Network",
            appleRating: 4.0,
            appleReviews: 516,
            avgLengthMinutes: 47,
            format: "Long form",
            since: "Dec 2009",
            description: "Culinary historian Linda Pelaccio takes a journey through the history of food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 26,
            name: "Austin All Day",
            hosts: ["Jason Powers", "Danny Kievit"],
            producer: "Austin All Day",
            appleRating: 4.8,
            appleReviews: 26,
            avgLengthMinutes: 80,
            format: "Long form",
            since: nil,
            description: "Culinary Tales - Tune in to Austin's culinary frequency. Take a rare listen to Austin's food scene.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 27,
            name: "The Sporkful",
            hosts: ["Dan Pashman"],
            producer: "SiriusXM Podcasts",
            appleRating: 4.6,
            appleReviews: 4400,
            avgLengthMinutes: 36,
            format: "Medium form",
            since: "Aug 2015",
            description: "We obsess about food to learn more about people. The Sporkful isn't for foodies, it's for eaters.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 28,
            name: "The Splendid Table: Conversations & Recipes For Curious Cooks & Eaters",
            hosts: ["Francis Lam"],
            producer: "American Public Media",
            appleRating: 4.3,
            appleReviews: 3100,
            avgLengthMinutes: 53,
            format: "Long form",
            since: "Jan 1999",
            description: "The Splendid Table has always connected people through the common language of food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 29,
            name: "The Food Chain",
            hosts: ["Ruth Alexander"],
            producer: "BBC World Service",
            appleRating: 4.7,
            appleReviews: 937,
            avgLengthMinutes: 28,
            format: "Medium form",
            since: nil,
            description: "The Food Chain examines the business, science and cultural significance of food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 30,
            name: "Three Food Memories",
            hosts: ["Savva Savas"],
            producer: "Savva Savas",
            appleRating: nil,
            appleReviews: 30,
            avgLengthMinutes: 29,
            format: "Medium form",
            since: nil,
            description: "The things you find out when you ask people about their food memories can be soulful, spicy.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 31,
            name: "Spilled Milk",
            hosts: ["Molly Wizenberg", "Matthew Amster-Burton", "Abby Cerquitella"],
            producer: "Molly Wizenberg and Matthew Amster-Burton",
            appleRating: 4.6,
            appleReviews: 1800,
            avgLengthMinutes: 32,
            format: "Medium form",
            since: "Jan 2010",
            description: "Every week on Spilled Milk, writers/comedians Molly Wizenberg and Matthew Amster-Burton discuss food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 32,
            name: "The Connected Table Live",
            hosts: ["Melanie Young", "David Ransom"],
            producer: "Talk 4 Podcasting",
            appleRating: 4.2,
            appleReviews: 5,
            avgLengthMinutes: 49,
            format: "Long form",
            since: nil,
            description: "Food and beverage industry insiders Melanie Young and David Ransom connect you to the world of food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 33,
            name: "Candy Is Dandy: The Candy Review Podcast",
            hosts: ["Greg Gonzalez", "Beto Sistos", "Daniel Zafran"],
            producer: "Candy Podcast",
            appleRating: 5.0,
            appleReviews: 69,
            avgLengthMinutes: 69,
            format: "Long form",
            since: nil,
            description: "The world's only candy review podcast. Like Doughboys, but for candy.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 34,
            name: "50 Tastes Of Gray",
            hosts: ["Matthew Gray"],
            producer: "Matthew Gray - 50TastesOfGray",
            appleRating: nil,
            appleReviews: nil,
            avgLengthMinutes: 49,
            format: "Long form",
            since: nil,
            description: "Aloha from Hawaii! I'm Matthew Gray, your Top Chef on the delightful journey of my culinary adventures.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 35,
            name: "Walk-In Talk Podcast",
            hosts: ["Carl Fiadini"],
            producer: "Carl Fiadini",
            appleRating: 4.9,
            appleReviews: 156,
            avgLengthMinutes: 45,
            format: "Long form",
            since: nil,
            description: "We are a Food Podcast. We are blessed to have been ranking on Apple Podcast Charts.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 36,
            name: "Dinner SOS by Bon Appétit",
            hosts: ["Chris Morocco"],
            producer: "Bon Appétit",
            appleRating: 4.2,
            appleReviews: 3100,
            avgLengthMinutes: 36,
            format: "Medium form",
            since: "Nov 2014",
            description: "A last-minute party with no menu inspiration. A kitchen with no space. A toddler who will only eat beige foods.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 37,
            name: "Dishing with Stephanie's Dish",
            hosts: ["Stephanie Hansen"],
            producer: "Stephanie Hansen - @StephaniesDish",
            appleRating: 5.0,
            appleReviews: 19,
            avgLengthMinutes: 31,
            format: "Medium form",
            since: nil,
            description: "I talk with Cookbook authors and Makers obsessed with food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 38,
            name: "FoodCrush",
            hosts: [],
            producer: "OnMilwaukee",
            appleRating: 4.6,
            appleReviews: 26,
            avgLengthMinutes: 74,
            format: "Long form",
            since: "Oct 2018",
            description: "Get hungry. On the FoodCrush podcast, OnMilwaukee Dining Editor Lori Fredrich explores Milwaukee's food scene.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 39,
            name: "Eater's Digest",
            hosts: ["Amanda Kludt", "Daniel Geneen"],
            producer: "Eater",
            appleRating: 4.0,
            appleReviews: 991,
            avgLengthMinutes: 46,
            format: "Long form",
            since: nil,
            description: "Everything you need to know about the world of food each week.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 40,
            name: "Thought About Food Podcast",
            hosts: ["Ian Werkheiser"],
            producer: "Ian Werkheiser",
            appleRating: 5.0,
            appleReviews: 12,
            avgLengthMinutes: 67,
            format: "Long form",
            since: "Sep 2020",
            description: "Each episode we look at important issues around food, and we talk to academics, activists, policymakers, nutritionists, chefs.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 41,
            name: "Bite",
            hosts: ["Tom Philpott", "Kiera Butler", "Maddie Oatman"],
            producer: "Mother Jones",
            appleRating: 4.3,
            appleReviews: 243,
            avgLengthMinutes: 28,
            format: "Medium form",
            since: "Mar 2016",
            description: "Bite is a podcast for people who think hard about their food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 42,
            name: "MCHEF BURST OF FLAVORS",
            hosts: ["Marie D. Rail", "Lee Cummings"],
            producer: "Marie-D. Rail & Lee Cummings",
            appleRating: 5.0,
            appleReviews: 3,
            avgLengthMinutes: 39,
            format: "Medium form",
            since: "Jun 2019",
            description: "This podcast inspires for a healthier and happier gourmet foodie-fit healthy nutrition.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 43,
            name: "The Gastronomy Club",
            hosts: ["Matthew Bu"],
            producer: "Matthew Bu",
            appleRating: 5.0,
            appleReviews: 13,
            avgLengthMinutes: 39,
            format: "Medium form",
            since: "Jun 2020",
            description: "The Gastronomy Club is a podcast that dives deep into the world of local restaurateurs.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 44,
            name: "Uncooked Women",
            hosts: ["Adaorah Oduah", "Lamisko"],
            producer: "Uncooked Women",
            appleRating: 4.9,
            appleReviews: 11,
            avgLengthMinutes: 37,
            format: "Medium form",
            since: "Mar 2020",
            description: "Joined by the most interesting people in West African gastronomy.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 45,
            name: "Sustainable Dish Podcast",
            hosts: ["Diana Rodgers"],
            producer: "Diana Rodgers",
            appleRating: 4.6,
            appleReviews: 326,
            avgLengthMinutes: 56,
            format: "Long form",
            since: "Oct 2014",
            description: "Sustainable Dish Podcast is a show hosted by nutritionist, author and sustainability advocate Diana Rodgers.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 46,
            name: "Journey to the Centre of Food",
            hosts: ["Heston Blumenthal"],
            producer: "Journey to the Centre of Food",
            appleRating: 4.9,
            appleReviews: 318,
            avgLengthMinutes: 51,
            format: "Long form",
            since: "Oct 2018",
            description: "For curious food lovers everywhere, jump onboard for a trip to discover the wonders of our simplest ingredients.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 47,
            name: "Burnt Toast",
            hosts: ["Michael Harlan Turkell"],
            producer: "Food52",
            appleRating: 4.1,
            appleReviews: 508,
            avgLengthMinutes: 22,
            format: "Medium form",
            since: "Feb 2015",
            description: "Food intersects with our lives in more ways than we think. Food52's Burnt Toast podcast explores those intersections.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 48,
            name: "Item 13: An African Food Podcast",
            hosts: ["Yorm Ackuaku"],
            producer: "Heritage Radio Network",
            appleRating: 5.0,
            appleReviews: 22,
            avgLengthMinutes: 49,
            format: "Long form",
            since: "Apr 2018",
            description: "A podcast on all things African food! Every other week, Host Yorm Ackuaku delves into the world of African cuisine.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 49,
            name: "Smart Mouth",
            hosts: ["Katherine Spiers"],
            producer: "Katherine Spiers / TableCakes Productions",
            appleRating: 4.8,
            appleReviews: 265,
            avgLengthMinutes: 41,
            format: "Long form",
            since: nil,
            description: "An addictively illuminating, often hilarious, conversational podcast about the surprising stories behind food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 50,
            name: "Curious Me Podcast",
            hosts: ["Mindy Musselman", "Emily Frisella"],
            producer: "Emily Frisella and Mindy Musselman",
            appleRating: 4.8,
            appleReviews: 558,
            avgLengthMinutes: 51,
            format: "Long form",
            since: nil,
            description: "We are back with an expanded show to share practical tips for health, food and fitness.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 51,
            name: "Pederson's Farms - Powered by Protein",
            hosts: ["Neil Dudley"],
            producer: "Pederson's Farms",
            appleRating: 5.0,
            appleReviews: 4,
            avgLengthMinutes: 26,
            format: "Medium form",
            since: nil,
            description: "Have you ever wondered where your food comes from? Welcome to the Pederson's Farms podcast.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 52,
            name: "Masters of Social Gastronomy",
            hosts: ["Sarah Lohman", "Jonathan Soma"],
            producer: "Sarah Lohman and Jonathan Soma",
            appleRating: 4.8,
            appleReviews: 11,
            avgLengthMinutes: 59,
            format: "Long form",
            since: "May 2012",
            description: "Each month, Masters of Social Gastronomy takes on a curious food topic and breaks down the history.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 53,
            name: "The Kitchen Counter - Home Cooking Tips and Inspiration",
            hosts: [],
            producer: "Kitchen Counter Media",
            appleRating: 4.4,
            appleReviews: 343,
            avgLengthMinutes: 38,
            format: "Medium form",
            since: "Sep 2014",
            description: "The show that's dedicated to helping aspiring home cooks grow their skills and confidence.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 54,
            name: "Richard's Famous Food Podcast",
            hosts: ["Richard Parks III"],
            producer: "Richard Parks III",
            appleRating: 4.9,
            appleReviews: 223,
            avgLengthMinutes: 20,
            format: "Short form",
            since: "Jul 2015",
            description: "'A stream of consciousness that explodes with clouds of color and aural wit.'",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 55,
            name: "Food Non-Fiction",
            hosts: ["Lillian Yang"],
            producer: "Lillian Yang",
            appleRating: 4.6,
            appleReviews: 364,
            avgLengthMinutes: nil,
            format: nil,
            since: nil,
            description: "Food Non-Fiction tells the incredible true stories behind food.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 56,
            name: "Radio Stories",
            hosts: ["David Preshaah"],
            producer: "David Preshaah",
            appleRating: nil,
            appleReviews: 3,
            avgLengthMinutes: 45,
            format: "Long form",
            since: "Apr 2021",
            description: "Radio stories with fans and friends of the media of radio sharing their memories and passion.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 57,
            name: "Food by Design: an IDEO Podcast",
            hosts: ["Sandeep Pahuja"],
            producer: "IDEO",
            appleRating: 4.9,
            appleReviews: 355,
            avgLengthMinutes: 23,
            format: "Medium form",
            since: "Sep 2020",
            description: "Our food system isn't broken, it was designed this way. And if it was designed this way, then it can be redesigned.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 58,
            name: "Turning Chickens and Breaking Dishes",
            hosts: ["Davide G. Martins"],
            producer: "Davide G. Martins",
            appleRating: 5.0,
            appleReviews: 46,
            avgLengthMinutes: 32,
            format: "Medium form",
            since: "Jul 2020",
            description: "My name is Davide G. Martins, and I'm the Executive Chef for the European Union Embassy.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 59,
            name: "Food on the Table",
            hosts: [],
            producer: "GiftAMeal",
            appleRating: 4.6,
            appleReviews: 11,
            avgLengthMinutes: 25,
            format: "Medium form",
            since: "Apr 2020",
            description: "Food on the Table brings you behind-the-scenes to meet the people who drive the food industry.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 60,
            name: "Crutchfield Cooks",
            hosts: ["Robert Crutchfield"],
            producer: nil,
            appleRating: nil,
            appleReviews: nil,
            avgLengthMinutes: 28,
            format: "Medium form",
            since: nil,
            description: "Restaurants, grocery stores, cooking, food news and more are fair game in this podcast.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 61,
            name: "Urban Philly Foodees",
            hosts: [],
            producer: nil,
            appleRating: nil,
            appleReviews: nil,
            avgLengthMinutes: nil,
            format: nil,
            since: nil,
            description: "Hey there, fellow foodies! Welcome to the Urban Philly Foodies Podcast, your ultimate guide to Philadelphia's food scene.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        ),
        FoodPodcastEntry(
            rank: 62,
            name: "The Kitchen Is On Fire",
            hosts: [],
            producer: nil,
            appleRating: nil,
            appleReviews: nil,
            avgLengthMinutes: nil,
            format: nil,
            since: nil,
            description: "A food podcast exploring culinary adventures and kitchen stories.",
            websiteUrl: nil,
            appleUrl: nil,
            spotifyUrl: nil
        )
    ]

    /// Get podcasts by format type
    static func podcasts(format: String) -> [FoodPodcastEntry] {
        allPodcasts.filter { $0.format?.lowercased() == format.lowercased() }
    }

    /// Get podcasts with rating above threshold
    static func podcasts(ratingAbove: Double) -> [FoodPodcastEntry] {
        allPodcasts.filter { ($0.appleRating ?? 0) >= ratingAbove }
    }

    /// Get top N podcasts by rating
    static func topRated(limit: Int = 10) -> [FoodPodcastEntry] {
        allPodcasts
            .filter { $0.appleRating != nil }
            .sorted { ($0.appleRating ?? 0) > ($1.appleRating ?? 0) }
            .prefix(limit)
            .map { $0 }
    }

    /// Get top N podcasts by review count
    static func mostReviewed(limit: Int = 10) -> [FoodPodcastEntry] {
        allPodcasts
            .filter { $0.appleReviews != nil }
            .sorted { ($0.appleReviews ?? 0) > ($1.appleReviews ?? 0) }
            .prefix(limit)
            .map { $0 }
    }

    /// Search podcasts by name or host
    static func search(query: String) -> [FoodPodcastEntry] {
        let lowercaseQuery = query.lowercased()
        return allPodcasts.filter { podcast in
            podcast.name.lowercased().contains(lowercaseQuery) ||
            podcast.hosts.contains { $0.lowercased().contains(lowercaseQuery) } ||
            podcast.producer?.lowercased().contains(lowercaseQuery) == true
        }
    }
}
